import "../styles/globals.css";
import { Poppins } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { CartProvider } from "@/app/context/CartProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html
      lang="en"
      className={`${poppins.variable} font-primary flex just-cont`}
    >
      <body
        className={`min-h-[100vh] w-[96rem] grid grid-rows-[auto,1fr,auto] bg-offWhite`}
      >
        <CartProvider>
          <Header />
          <main className="overflow-hidden">{children}</main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
};

export default Layout;
